# Site
name: 'CBSI - IFS Lagarto'
coordenadoria: "Coordenadoria de Sistemas de Informação"
campus: "Lagarto"
description: 'Site, não oficial, da coordenadoria de Sistemas de Informação do Campus Lagarto.'
logo: 'assets/images/CBSI-logo.jpg'
favicon: 'assets/images/favicon.ico'
baseurl: "/mundana-theme-jekyll"
# TODO
#disqus: 'demowebsite'
#email: 'wowthemesnet@gmail.com'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

# Exemplo de temas http://preview.themeforest.net/item/devoll-multipurpose-theme-powered-by-jekyll/full_screen_preview/11132266?_ga=2.52203681.921556940.1566450303-1009772003.1566028252&irgwc=1&clickid=Rc50MFUzjxyOUPowUx0Mo3IyUkix650fZR%3Ay0c0&iradid=275988&irpid=420717&iradtype=ONLINE_TRACKING_LINK&irmptype=mediapartner&mp_value1=&utm_campaign=af_impact_radius_420717&utm_medium=affiliate&utm_source=impact_radius





include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-timeago
  # Olhar https://github.com/psmiraglia/jekyll-email-obfuscator
  # Plugin para filtrar em coleções https://gist.github.com/delputnam/5496ada2a6e009e8e578


  # Documentação legal https://bl.ocks.org/roachhd/2909c695979764498922

jekyll_timeago:
  depth: 2
  translations_path: '/assets/libs/jekyll_timeago/*.yaml'
  default_locale: 'pt'
  fallbacks: true
  available_locales:
    - 'en'
    - 'es'
    - 'fr'
 
collections:
  equipe:
    output: true
    permalink: /equipe/:path/
    sort_by: name


# Defaults
defaults:
  - scope:
      path: ""
      type: "equipe"
    values:
      layout: "pessoal"
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      categories: [ Geral ]
      #author: sal
      #avatar: logo
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10
paginate_trail: 2
paginate_show_first_and_last: true

sass:
  sass_dir: _sass
  style: :compressed


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]